repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.950'
    hooks:
    -   id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
        args: ["--profile=black"]
  - repo: https://github.com/ambv/black
    rev: '22.3.0'
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: ["--max-line-length=139"]
